version: '3'

services:
  0gchnode0:
    container_name: 0gchnode0
    image: "0glabs/0gchain-node"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-kvd.log}
    volumes:
      - ./build:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  0gchnode1:
    container_name: 0gchnode1
    image: "0glabs/0gchain-node"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-kvd.log}
    volumes:
      - ./build:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  0gchnode2:
    container_name: 0gchnode2
    image: "0glabs/0gchain-node"
    environment:
      - ID=2
      - LOG=${LOG:-kvd.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  0gchnode3:
    container_name: 0gchnode3
    image: "0glabs/0gchain-node"
    environment:
      - ID=3
      - LOG=${LOG:-kvd.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/kvd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
